provider "aws" {
  region = var.region
}

locals  {
  instance_name       = "tf-${terraform.workspace}-${var.instance_name}"
}

resource "aws_instance" "test_ec2" {
  ami           = var.ami_id
  instance_type = var.instance_type
  key_name      = var.key_name
  vpc_security_group_ids      = [aws_security_group.tf-security-group.id]

  tags = {
    Name = local.instance_name
  }

  provisioner "remote-exec" {

    connection {
      type        = "ssh"
      user        = var.user_instance
      private_key = file(var.access_key_path)
      host        = self.public_ip
      timeout     = "5m"
    }

    inline = [
      "echo 'This is a file generated by Terraform on the instance' > new-test.txt"
    ]
  }
}